### ISSUE TITLE
Expand CLI argument documentation

### ISSUE THREAD

**Issue by ophilli** [jscarrott/mdbook-combiner#29]
It is not immediately obvious to me how the "jabom" and "inject_titles" arguments are intended to be used.

https://github.com/jscarrott/mdbook-combiner/blob/e43262bf710758a3a3169833c6c0ee601638b28a/src/main.rs#L11-L21

It would be nice to expand the help text here.

**Comment by jscarrott** [comment]
Sure, I always meant to come back and fix up the documentation. In brief jabom(Just a bunch of markdown) can take a folder with markdown files and generate the summary file for it. In this way if you have say a github wiki that you want to combine with a mdbook summary you can do something like -m foo -j bar (Where foo is a folder containing the existing summary files and bar is the wiki folder)

Inject titles is a bit of a hack I added to solve a search problem. The titles of each page don't get indexed by the mdbook search, which is fine with a hand crafted summary but not a great experience with importing a wiki say. That option injects the titles of each page into the markdown text so they are picked up by the search. Not pretty but it makes the search usable in those cases.

**Comment by ophilli** [comment]
Thanks for the extra context @jscarrott! I cut #30 to edit the doc comments for the arguments. Can you take a look at your earliest convenience?

**Comment by jscarrott** [comment]
Fixed in [0.1.15](https://github.com/jscarrott/mdbook-combiner/releases/tag/v0.1.15)
